### ISSUE TITLE
Implementing details of copy and repeated copy tasks

### ISSUE THREAD

**Issue by TreeLimes** [MarkPKCollier/NeuralTuringMachine#10]
Say we are considering the copy task and we want to give a sequence of length 10 to our model. So, following the code, we actually give our controller a sequence of length 21, where the 11th element is an end of sequence marker (a vector of 1s) and the last 10 elements are vectors of 0s. Where does the code specify that the output should start at the end of sequence marker?

Now, for the repeated copy task, it doesn't seem like we should provide the target output size the same way we do in the copy task. For example, given a sequence of length 10 that is to be copied 2 times, it wouldn't make sense to give as input a sequence of 31 vectors since we want the model to learn when to stop copying. So how should the input be structured in this case?

**Comment by MarkPKCollier** [comment]
> Say we are considering the copy task and we want to give a sequence of length 10 to our model. So, following the code, we actually give our controller a sequence of length 21, where the 11th element is an end of sequence marker (a vector of 1s) and the last 10 elements are vectors of 0s. Where does the code specify that the output should start at the end of sequence marker?

See the following code in the `run_tasks.py` script:

```
if args.task == 'copy':
    self.output_logits = output_sequence[:, self.max_seq_len+1:, :]
elif args.task == 'associative_recall':
    self.output_logits = output_sequence[:, 3*(self.max_seq_len+1)+2:, :]
```

> Now, for the repeated copy task, it doesn't seem like we should provide the target output size the same way we do in the copy task. For example, given a sequence of length 10 that is to be copied 2 times, it wouldn't make sense to give as input a sequence of 31 vectors since we want the model to learn when to stop copying. So how should the input be structured in this case?

The `run_tasks.py` script does not presently support the repeat copy task, but you can easily modify it to do so as the `generate_data.py` script contains the class to generate the data for the repeat copy task. You may find it helpful to look at https://github.com/MarkPKCollier/CurriculumLearningFYP/blob/master/tasks/run_tasks.py if you wish to do this.
