### ISSUE TITLE
Error 'tuple unpacking is not supported in Python3'

### ISSUE THREAD

**Issue by amirbidokhti** [MarkPKCollier/NeuralTuringMachine#3]
Hi @MarkPKCollier 

I wanted to run the code using python 3.6, an error occurs in file 'generate_data.py', Line: 263

```
File "D:\...\NeuralTuringMachine-master\generate_data.py", line 263
    outputs = map(lambda (source, dest, edge):
                         ^
SyntaxError: invalid syntax
```

and it seems that the error is because 'tuple unpacking is not supported in Python3'.

What can I do? switch to Python 2?

Thank you.

**Comment by MarkPKCollier** [comment]
Hey,

Thanks for catching this.

I believe the following should work with Python 3:

`outputs = map(lambda t:`

and then just access the tuple items like `t[0]`.

I've pushed this change, let me know if it works for you. I didn't check if the rest of the code's Python 3 compatibility. If any other issues crop up feel free to open a PR.

**Comment by amirbidokhti** [comment]
Yes, I made corrections like this

Code which works on Python 3:

`outputs = map(self.my_concat, path)`

and I also defined this function before `def generate_item`
```
    def my_concat(self, input):
        return np.concatenate((
            graph_label_to_one_hot(input[0]),
            graph_label_to_one_hot(input[1]),
            graph_label_to_one_hot(input[2])
        ))
```

Now it works on Python 3.6 with no problem.

thank you.
