### ISSUE TITLE
where I can find the formula that generate head parameters

### ISSUE THREAD

**Issue by scotthuang1989** [MarkPKCollier/NeuralTuringMachine#6]
sorry for the silly question. I am an engineer, not a researcher(I don't have a strong backgroud on theory and math). 
I try to apply this external memory idea on my work. I read the original NTM paper: 1410.5401 and your paper, I can't find the formula that generate these head parameters: 
 **k, beta, g, s gamma**.  

Do I miss something or there are some "common knowledge" for this kind of parameter?

**Comment by MarkPKCollier** [comment]
These parameters are outputs of the controller network. Exactly how you decide to set this up is a free choice, but we just perform a linear transformation on the controller hidden state i.e. matrix multiply of LSTM memory units.

In addition, there are conditions on these parameters which are stated in the original paper: β ≥ 0, g ∈ [0, 1], γ ≥ 1, s must be non negative and sum to 1.

So we must apply appropriate non-linearities to the result of the linear transformation. There are standard non-linearities used that satisfy these requirements, some of which were specified in the original paper and others are in our paper e.g. the sigmoid non-linearity will satisfy g ∈ [0, 1].

**Comment by scotthuang1989** [comment]
thanks for the quick  answer.
