### ISSUE TITLE
Different type of memory for NTMs

### ISSUE THREAD

**Issue by ghost** [MarkPKCollier/NeuralTuringMachine#7]
Maybe you could use locality sensitive hash (LSH) associative memory for NTMs?
http://gamespace.eu5.org/associativememory/index.html

**Comment by MarkPKCollier** [comment]
Not familiar with LSH, but from a brief read through it looks like this addressing scheme wouldn't be differentiable which is a key contribution of the NTM. In any case the addressing scheme is part of what defines a NTM so an associative memory with LSH addressing wouldn't be a NTM it would be something else.

**Comment by ghost** [comment]
You can replace the hard binarization with a softer version.  Eg. The signed square root fuction y=sqr(x) x>=0, y=-sqr(-x) x<0.   Which has attractor points at +1 and -1.  Also the random projection I indicated is invertible.
Don't see what can't be differentiated. 
Anyway, up to you.  
Also I evolve neural networks with ES and many of the issues around BP have little significance to me.
Though there may not be that much difference between what BP and evolution can do because some recent papers show that there are no trapping local minimums in large networks, just lots of saddle points to slow learning down and make it more sequential/incremental in nature.



 

    On Saturday, April 6, 2019, 12:06:25 AM GMT+8, Mark Collier <notifications@github.com> wrote:  
 
 
Closed #7.
